Picture in Picture support
iina/iina pull request #165
Opened 2017-01-14 04:38 UTC by saagarjha

This pull request adds support for Picture in Picture. I would advise against merging this as-is, since it still needs a bit of work. I just wanted to get your feedback on it.

A couple of things that need addressing:

* Crash when switching between Picture in Picture and "normal" too quickly using the keyboard shortcut (Command+Shift+P)
* Some way of alerting the user on the main window that the video is playing as Picture in Picture
* You tell me

2017-01-14 05:39 UTC, matthewdias commented
Could probably either do it Safari style, with a label on the window indicating PIP mode, or maybe just hide the window entirely?

2017-01-14 05:49 UTC, saagarjha commented
I think hiding the window could lead to user confusion–plus, the controls for things like scrubbing and volume control are on the control bar. I'm thinking of adding a `NSVisualEffects` view with a label on it ("This video is playing in Picture in Picture") to replace the video view.

2017-01-19 01:50 UTC, saagarjha commented
@matthewdias I've added an `NSVisualEffectView`+label.

2017-01-21 05:52 UTC, lhc70000 commented
Sorry for reverting some changes on `develop`.

When updating your branch, it's better and cleaner to use git rebase rather than merge.

2017-01-21 06:06 UTC, saagarjha commented
Sure, no problem. Thankfully `project.pbxproj` is plain text, and not a binary file!

2017-02-04 00:53 UTC, saagarjha commented
@lhc70000 I've remedied the conflicts. Please give this a thorough check, since I was forced to solve quite a few merge conflicts by hand (in the XIBs no less), so I can't guarantee that everything functions as expected. Please try out the new features you've added in 0.0.4 and see if they work. Keeping up with IINA's changes is hard, so the sooner this gets merged the easier it is for me.

2017-02-04 08:20 UTC, lhc70000 commented
I'll take a look tomorrow (too busy today, sorry)

2017-02-04 08:21 UTC, saagarjha commented
Sure, no problem.

2017-02-06 12:13 UTC, lhc70000 commented
Could you resolve the conflicts? (sorry, this is the last time)

2017-02-07 17:56 UTC, saagarjha commented
@lhc70000 Done.

2017-02-08 15:05 UTC, lhc70000 requested changes

2017-02-08 15:05 UTC, lhc70000 commented on iina/PlayerCore.swift
> +      statusPaused = !statusPaused
Seems that `statusPaused` is an unused field. Please delete it directly, and use `playerCore.info.isPaused` instead.

2017-02-08 16:53 UTC, saagarjha commented on iina/MainWindowController.swift
> +	@IBOutlet weak var pipOverlayView: NSVisualEffectView!
Interface Builder does that–I've been meaning to file a Radar.

2017-02-08 16:54 UTC, saagarjha commented on iina/MainWindowController.swift
> +      if controlBar.isDragging || isInPIP { return }
Good idea; I've moved all the checks to `hideUI()`.

2017-02-08 16:54 UTC, saagarjha commented on iina/MainWindowController.swift
> +    guard !isInPIP else { return }
Not sure why I put it so high up; I've moved it down in the function.

2017-02-08 16:54 UTC, saagarjha commented on iina/MainWindowController.swift
> +      let scale = origWidth == currWidth ? winFrame.width / currWidth: winFrame.height / currHeight
Yes.

2017-02-08 16:55 UTC, saagarjha commented on iina/MainWindowController.swift
> +        } else { // Force Touch or long press ended
Sorry, I couldn't resist :)

2017-02-08 16:55 UTC, saagarjha commented on iina/MenuController.swift
> +
Got it.

2017-02-08 16:55 UTC, saagarjha commented on iina/PlayerCore.swift
> +      statusPaused = !statusPaused
Alright, it's deleted.

2017-02-09 15:51 UTC, lhc70000 approved these changes

2017-02-09 15:53 UTC, merged

2017-02-13 00:02 UTC, matthewdias commented
@saagarjha @lhc70000 the aspect ratio gets messed up when exiting fullscreen.

- open vid in fullscreen with a display with a different aspect ration than the video
- switch to pip
- exit fullscreen

pip will get resized to aspect ratio of the display, and vid is stretched across it.

2017-02-13 00:05 UTC, matthewdias commented
also the pip getting resized happens when you first enter pip while in fullscreen. it is letterboxed until you exit fullscreen, at which point it stretches.

2017-02-13 00:40 UTC, saagarjha commented
I believe that this may be due to b2fba05633e1cb41f7a6f0b0a305404c77f42149. @lhc70000 would you mind reminding me on how resizing/scaling works?

2017-02-13 08:35 UTC, lhc70000 commented
@saagarjha It was handled manually prior to 0.0.4, but now the view always has the same size with window and let mpv to handle letterboxes in full screen, and the layer size is queried at realtime when drawing each frame. Aspect ratio in window mode is only locked by window's aspect ratio.

So `videoView.videoSize` is actually unused now. There may be two options:
- stop updating `videoSize` in full screen, or
- remove `videoSize` and get the actual size from `playerCore.info.videoWidth` and `.videoHeight`.

2017-02-13 09:25 UTC, lhc70000 commented
Just pushed a quick fix (get the actual size from `playerCore.info.videoWidth` and `.videoHeight`) as 0.0.5 will be released soon.