Add function to save playlist.
iina/iina pull request #264
Opened 2017-01-25 02:44 UTC by inflation

In order to fix #263.

2017-01-28 18:55 UTC, lhc70000 commented on iina/MainWindowMenuActions.swift
> +    let _ = Utility.quickSavePanel(title: "Save to playlist", types: ["m3u8"], ok: {
Please use trailing closure:
```
Utility.quickSavePanel(title: "Save to playlist", types: ["m3u8"]) {
  ...
}

2017-02-09 21:03 UTC, lhc70000 requested changes

2017-02-09 21:03 UTC, lhc70000 commented on iina/MainWindowMenuActions.swift
> +          print(error.localizedDescription)
Please show an alert to user, or at least use `Utility.log`

2017-02-09 21:03 UTC, lhc70000 commented on iina/Utility.swift
> +      return true
Better return `false` when `url` is `nil`?

2017-02-10 02:10 UTC, alejx commented
A suggestion. What about create a new file format for IINA playlist instead of m3u8? Just in case of adding any future fancy functions into the playlist.

2017-02-10 02:11 UTC, alejx commented
Add a keyboard shortcut like `cmd+shift+s`?

2017-02-10 02:31 UTC, inflation commented on iina/Utility.swift
> +      return true
For these panels, we don't check the return value anyway. Checking url's non-emptiness seems to be done all in the callbacks.

2017-02-10 02:47 UTC, inflation commented
@alejx I would more like to keep with the open standard. You don't want users to find the exported playlist cannot be opened elsewhere.

2017-02-12 08:47 UTC, lhc70000 approved these changes

2017-02-12 08:48 UTC, merged