[WIP] Enable Drag and Drop in Playlist TableView.
iina/iina pull request #269
Opened 2017-01-25 16:22 UTC by alejx

- Drag files from Finder to the playlist.
- Reorder rows in playlist.
- No more click to play item in playlist, use double click instead.
- [WIP] Multiple selection in playlist table view.

I deleted PlaylistDragDestView.swift and put all the stuff in the tableview instead.
Currently PlaylistTableDelegate seems like not useful at all (because it will no longer response click action), but I left it in PlaylistViewController.swift in case of future usage. If it is better to delete it I'll push a commit about it.

2017-02-09 21:57 UTC, lhc70000 requested changes
Only some suggestions on grammar. Didn't understand the algorithm yet, let me go through it tmr...

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      for i in Array(0...playlistCount).reversed() {
`(0...playlistCount).reversed()` should work?

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      let playlistCount = tableView.numberOfRows - 1
better get from data, i.e. `playerCore.info.playlist`

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      var order: Array<Int> = Array(0...playlistCount)
better use `[Int]` instead of `Array<>`

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +}
indent

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      for selectedRow in indexSet.reversed() {
No need to inverse twice

```swift
let reversedIndexSet = dataArray[0].reversed()

for ... in let reversedIndexSet {
  ...
}
```

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      var playing: Int = 0
no need for `: Int`

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +          playerCore.mpvController.command(.playlistMove, args: [(insertPosition + 1).toStr(), insertPosition.toStr()])
better add a wrapper in `PlayerCore`, like `playlistMove(from:_, to:_)`

2017-02-09 21:57 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      NotificationCenter.default.post(Notification(name: Constants.Noti.playlistChanged))
Maybe no need for this notification, since it's always posted when `playlist/count` changed

2017-02-09 22:33 UTC, alejx commented on iina/PlaylistViewController.swift
> +      var order: Array<Int> = Array(0...playlistCount)
Just curious, what's the diffierence?

2017-02-09 22:46 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      var order: Array<Int> = Array(0...playlistCount)
No difference, just for better formatting. `[ ]` is a syntax sugar specially designed for this, so why not?

2017-02-09 22:55 UTC, alejx commented on iina/PlaylistViewController.swift
> +      var order: Array<Int> = Array(0...playlistCount)
Gotcha.

2017-02-09 22:58 UTC, alejx commented on iina/PlaylistViewController.swift
> +      var playing: Int = 0
Just curious, is it supposed to be used as few as we can?

2017-02-09 23:02 UTC, alejx commented on iina/PlaylistViewController.swift
> +          playerCore.mpvController.command(.playlistMove, args: [(insertPosition + 1).toStr(), insertPosition.toStr()])
If I can add method in `PlayerCore`, I want to add an `insertToPlaylist(path:_, to:_)` to make code in `PlaylistViewController` more clear. What do you think?

2017-02-09 23:06 UTC, alejx commented on iina/PlaylistViewController.swift
> +      NotificationCenter.default.post(Notification(name: Constants.Noti.playlistChanged))
I tried, but after dropping, the playlist view did not refresh.

2017-02-09 23:14 UTC, lhc70000 commented on iina/PlaylistViewController.swift
> +      var playing: Int = 0
Sometimes it's better to clarify the type for readability, but `Int` is a simple type (that can be inferred easily by complier) and also the default type for integer literals, so better omit for simplicity.

```swift
var x = 0  // x is Int by default
var x: UInt32 = 0  // other int types
```

2017-02-09 23:15 UTC, alejx commented on iina/PlaylistViewController.swift
> +      var playing: Int = 0
Sounds good!

2017-02-09 23:28 UTC, alejx commented
@lhc70000 Ready for merge.

2017-02-11 08:12 UTC, lhc70000 approved these changes

2017-02-11 08:12 UTC, merged