added french translation
iina/iina pull request #298
Opened 2017-01-30 18:35 UTC by superzazu

French translation for the project; thanks @Solaarmoon & @metacosm for your work. Feel free to check if everything is okay :)

2017-01-31 10:01 UTC, metacosm commented
Looks good to me. 👍

2017-02-02 18:10 UTC, lhc70000 commented
Does this contains all features introduced in 0.0.4?

Also, if you don't mind, I prefer waiting for a few days and adding translations needed for 0.0.5 before merge.

2017-02-03 13:25 UTC, metacosm commented
The features introduced in 0.0.4 should be translated, yes. I will take a look at what's needed for 0.0.5.

2017-02-12 09:42 UTC, lhc70000 commented
Please update to latest `develop` branch and read [https://github.com/lhc70000/iina/issues/291#issuecomment-279206928](https://github.com/lhc70000/iina/issues/291#issuecomment-279206928).

2017-02-12 15:50 UTC, metacosm commented
Working on it.

2017-02-12 20:54 UTC, metacosm requested changes

2017-02-12 20:54 UTC, metacosm commented on iina/fr.lproj/KeyBinding.strings
> +"cmd.cycle" = "Cycler";
Alterner, peut-être?

2017-02-12 20:54 UTC, metacosm commented on iina/fr.lproj/Localizable.strings
> +"pl_menu.clear_playlist" = "Vider la playlist";
playlist -> liste de lecture?

2017-02-12 20:54 UTC, metacosm commented on iina/fr.lproj/Localizable.strings
> +"pl_menu.play_next" = "Écouter ensuite";
Écouter -> Jouer?

2017-02-12 20:57 UTC, superzazu commented on iina/fr.lproj/KeyBinding.strings
> +"cmd.cycle" = "Cycler";
Bonne idée, je n'y avais pas pensé ! :-)

2017-02-12 20:58 UTC, superzazu commented on iina/fr.lproj/Localizable.strings
> +"pl_menu.play_next" = "Écouter ensuite";
Exact, erreur de ma part.

2017-02-12 20:59 UTC, superzazu commented on iina/fr.lproj/Localizable.strings
> +"pl_menu.clear_playlist" = "Vider la playlist";
Au début de la traduction, j'ai effectivement hésité entre ces deux termes; avant de constater qu'Apple utilise le terme "playlist" sur iTunes. Du coup, j'ai gardé le terme pour toute la traduction :)

2017-02-12 21:24 UTC, metacosm commented on iina/fr.lproj/Localizable.strings
> +"pl_menu.clear_playlist" = "Vider la playlist";
👍

2017-02-13 08:03 UTC, superzazu commented
Okay it seems everything is mergeable :-)
Thanks @metacosm !

2017-02-13 10:09 UTC, merged