Multiple fixes to key binding parsing
iina/iina pull request #3887
Opened 2022-07-22 21:38 UTC by svobs

- [ ] This change has been discussed with the author.
- [x] It implements / fixes issues:
   #3831 
   #3881 
   #3851

---

**Description:**
This patch is a subset of (and is actually back-ported from) #3847, and contains only the changes to parsing and mapping key bindings. It is the successor to #3833: it fixes a loophole in that logic which result in unused duplicate entries being stored, while also adding other fixes which couldn't be merged separately.

It does the following
- Splits `KeyMapping`'s `key` field into rawKey and `normalizedMpvKey`, similar to how its `action` field has raw & parsed version.
- Moves the existing mpv normalization logic out of the `KeyMapping` constructor and into `KeyCodeHelper`.
- Expands the mpv normalization logic to ensure that in normal form (fixes #3851):
  - Special key symbols are capitalized
  - A key's uppercase symbol is used if it is available, instead of containing "Shift+"
  - Key sequences containing the `-` (minus) key are properly parsed
- Use normal form always when identifying key bindings; use raw form when editing in the UI, to ensure consistent functionality while keeping a smooth user experience
- Add check for ignoring the line `default-bindings begin`, rather than binding it to a ke
- Add check for `{section_name}` (section name in curly braces): if it is "default" then strip the section and include the binding; for other section names do not include the binding (fixes #3881)

2022-10-18 07:57 UTC, uiryuu commented on iina/KeyCodeHelper.swift
> +        case SHIFT_KEY: modifiers.insert(.shift)
Remove the space

2022-10-19 03:58 UTC, svobs commented
I made another commit based on more recent code - this was a little out of date - and fixed typos. The only significant change was that it needed a check for the special line `default-bindings start` so it didn't look ugly in the UI (even though IINA ignores it otherwise).

2022-10-20 10:54 UTC, svobs commented
Ack - found a bug - and just committed the fix. It incorrectly parsed if the rawKey included ended in the minus key (`-`) but also had modifiers (example: `Meta+-`". Updated my tests to include that...

2022-10-21 02:47 UTC, svobs commented
Found one more corner case with key sequences that wasn't handled (`--d--`). Swift's substring handling is really clunky...

I cleaned up the dash checks in `getNextEndIndex()` and added some comments. Sorry. Final answer this time.

2022-10-23 01:26 UTC, lhc70000 requested changes
Regarding the mpv key sequence part: It's great to handle key sequences (and we probably should add support for them later), but since IINA doesn't support key sequences, perhaps currently we should filter them out before displaying/setting the key bindings?

2022-10-23 01:26 UTC, lhc70000 commented on iina/AppData.swift
> +  static let iinaCurrentInputConfChanged = Notification.Name("IINACurrentInputConfChanged")
These names are unused?

2022-10-23 01:26 UTC, lhc70000 commented on iina/PlayerCore.swift
> +        Logger.log("Skipping line: \"default-bindings start\"", level: .verbose)
Why don't we drop the `default-bindings` line when parsing the conf file?

2022-10-23 01:26 UTC, lhc70000 commented on iina/PlayerCore.swift
> +        if let kb = filterSectionBindings($0) {
Can be `} else if let kb = ... {`

2022-10-23 01:50 UTC, uiryuu requested changes
Didn't test for the issues linked, hopefully that has been done by someone else. Just some suggestions based on the code.

2022-10-23 01:50 UTC, uiryuu commented on iina/KeyCodeHelper.swift
> +    }
```suggestion
    let normalizedList = keystrokesList.map({ normalizeSingleMpvKeystroke($0) })
```

2022-10-23 01:50 UTC, uiryuu commented on iina/KeyCodeHelper.swift
> +   MPV accepts several forms for the same keystroke. This ensures that it is reduced to a single standardized form
```suggestion
   mpv accepts several forms for the same keystroke. This ensures that it is reduced to a single standardized form
```

2022-10-24 00:40 UTC, svobs commented
I pushed a new commit, non-forced so you can see the changes.

> Why don't we drop the default-bindings line when parsing the conf file?

I agree it's not pretty to put it here, but it's hard to find another place to put it. If we drop the line while parsing the file, we'll end up removing it from the file the first time the user makes any other changes to it, because of the way config files are handled. It's one thing to strip the comments out of a file, but it's bigger thing to strip valid lines out of it, and I'd rather avoid doing that (and this is basically a section start token, so the consequences would be big). There are apparently some users who use the same config files for both IINA and mpv, and they would be adversely affected by it. 

> Regarding the mpv key sequence part: It's great to handle key sequences (and we probably should add support for them later), but since IINA doesn't support key sequences, perhaps currently we should filter them out before displaying/setting the key bindings?

Fair point. I've updated the normalization code to just pass back anything with more than one`-` in it. In practice this will cause key sequences to always fail to match against typed characters (as it was doing before).

2022-10-24 01:15 UTC, svobs commented
Now I see that changes are still retained either way, so I force pushed against the original commit, for tidiness.

2022-10-24 02:00 UTC, uiryuu approved these changes

2022-10-28 04:09 UTC, merged