Update rightLabel when clicked while player paused
iina/iina pull request #3913
Opened 2022-08-17 01:24 UTC by decodism

- [ ] This change has been discussed with the author.
- [x] It implements / fixes issue #3849.

2022-10-17 22:14 UTC, low-batt commented on iina/MPVController.swift
> +              if ![.willShow, .shown].contains(player.mainWindow.animationState) { player.invalidateTimer() }
This fixes the problem, but is undesirable from an energy use perspective. We absolutely do not want the timer to run when playback is paused and therefore the video position is not changing.

2022-10-17 22:43 UTC, low-batt requested changes
The timer that updates the UI is still running when it should not, wasting energy. That is why this problem seemed to be fixed.  The fix for this issue should not rely upon that timer running. We want to get to the point where that timer is only run when playback is active and the OSC is visible. We have been moving in that direction, but more changes are needed. So this fix can not depend up the timer updating the label.

I suggest the fix follow the normal pattern for handling changes in a control. 

One way to do this would be to add a `didSet` property observer to the `DurationDisplayTextField` `mode` property. This observer would call `updateText` to update the `stringValue` `NSTextField` property. Then the observer would set [needsDisplay](https://developer.apple.com/documentation/appkit/nsview/1483360-needsdisplay) to true.

To be able to call `updateText` `DurationDisplayTextField` needs to know the duration and position. That means adding properties and changing `updateText` to remember the values used to generate the string.

Something like that.

2022-10-18 00:29 UTC, decodism commented
I reverted to my previous fix and implemented your suggestion.

2022-10-18 03:11 UTC, low-batt approved these changes
Changes look good. I pulled the PR locally and confirmed the fix works.

2022-10-18 06:41 UTC, uiryuu approved these changes

2022-10-18 06:41 UTC, uiryuu commented
Thanks for your PR!

2022-10-18 06:41 UTC, merged