Fix toggle menus to adhere to HIG, #3116
iina/iina pull request #3980
Opened 2022-10-12 20:32 UTC by low-batt

This commit will change these toggle menus to use "Hide" in their title instead of "Show" when selecting the menu item hides the panel:
- Show Chapters Panel
- Show Playlist Panel
- Show Quick Settings Panel

This commit adds text that will require localization.

This fix only corrects one part of the reported issue. The behavior of buttons still needs to be updated to adhere to the HIG.

- [ ] This change has been discussed with the author.
- [x] It implements / fixes issue #3116.

---

**Description:**
This PR replaces the original PR, removing localization files.

2022-10-13 03:39 UTC, uiryuu commented on iina/Base.lproj/Localizable.strings
> +"menu.chapters" = "Show Chapters Panel";
Please also add new strings into `en.lproj/Localizable.strings`, otherwise Crowdin won't pick them up.

2022-10-13 08:05 UTC, uiryuu requested changes
The inconsistency annoys me. Currently there are `Show Playlist Panel` and `Show Chapter Panel` in the playback menu, but in it is `Show Quick Settings Panel` in Video, Audio, and Subtitle menu.

We should rename them into `Show Video/Audio/Subtitle Panel` and `Hide Quick Settings Panel` correspondingly.

2022-10-14 03:20 UTC, low-batt commented
The inconsistency in menu item names is due to the inconsistency in the menu structure. Using Video, Audio and Subtitles in the item names seems like duplicate text. Menu items according to the HIG are supposed to use "a condensed style". Of course you can argue that we are already violating that with items such as "Audio filters...". I can go ahead and make this change and we can see how it looks.

At the moment I am distracted by the fact that this fix is not working. MainWindowController has changed. The sideBarStatus used to indicate which panel was set, .settings or .playlist. That is no longer working. It is set to .settings when the playlist/chapter panel is being displayed. So the menus are malfunctioning.

Was hoping to post an additional commit that as requested adds the english translations. But I need to investigate why the sideBarStatus seems to be incorrect. A quick fix did not work. Need to dig into what happened in the MainWindowController code.

Tomorrow busy. Might be able to post an update Saturday.

2022-10-14 04:00 UTC, uiryuu commented
> Using Video, Audio and Subtitles in the item names seems like duplicate text. 

Sorry I didn't make it clear. I meant we should rename them into
- `Show Audio Panel`
- `Show Video Panel`
- `Show Subtitle Panel`
in the corresponding menu

2022-10-14 04:29 UTC, uiryuu commented
> The sideBarStatus used to indicate which panel was set, .settings or .playlist. That is no longer working.

@low-batt This is caused by 60b944f when copy-pasting the reused code. I've pushed the fix, please pull and try.

2022-10-14 18:19 UTC, low-batt commented
I picked up the commit and confirmed that fixes the problem.
I need to rename the menu items. Tied up today. I should be able to get that done tomorrow.

2022-10-15 02:51 UTC, low-batt commented
I've renamed the menu items. This does create a slight inconsistency with the buttons used in the OSC:

![issue-3116](https://user-images.githubusercontent.com/86170219/195965582-8983a27f-9cc3-4611-a2fb-390265ae9553.jpg)

Should `Quick Settings` be renamed to  `Video, audio and subtitles`?

2022-10-15 07:23 UTC, saagarjha commented
What’s the inconsistency?

2022-10-15 18:02 UTC, low-batt commented
I remembered this morning that I forgot to update MainMenu.xib. Even though the text in the xib is not used it should be updated to not confuse developers. So that needs to be changed before this PR is ready to be merged.

On the question about the button inconsistency...

Currently the menu items are:
- Show Quick Settings Panel
- Show Chapters Panel
- Show Playlist Panel

And the OSC buttons are:
- Quick Settings
- Playlist and chapters

So it is clear that the `Quick Settings` button corresponds to `Show Quick Settings Panel`.

By renaming the menu items to make them more consistent:
- Show Video Panel
- Show Audio Panel
- Show Subtitles Panel
- Show Chapters Panel
- Show Playlist Panel

We have eliminated the term "Quick Settings" and broken the correspondence with the OSC button.

If we want to proceed with the change to the menu items then I think the buttons should be renamed as well:
- Video, audio and subtitles
- Playlist and chapters

Should I go ahead and change the button name as well?

2022-10-17 01:04 UTC, uiryuu commented
> Should Quick Settings be renamed to Video, audio and subtitles?

No, "Quick Settings" means the video panel + audio panel + subtitle panel.

2022-10-17 01:11 UTC, uiryuu approved these changes

2022-10-17 02:39 UTC, low-batt commented
How does the user know what "Quick Settings" means now that we removed that text from the menus? The panel itself has no such label. That was my worry.

Should I also update the menu item text in MainMenu.xib? It gets overwritten, but if I leave it set to "Show Quick Settings Panel" it could confuse a developer.

2022-10-17 02:49 UTC, uiryuu commented
> How does the user know what "Quick Settings" means now that we removed that text from the menus? The panel itself has no such label. That was my worry.

I think this is a valid concern, but since we have used "Quick Settings" for years in IINA, removing that will also surprise some of the users. I think we can discuss this in another issue, let's get this merged first!

> Should I also update the menu item text in MainMenu.xib? It gets overwritten, but if I leave it set to "Show Quick Settings Panel" it could confuse a developer.

Yes please do that. That should change the corresponding text in `Base.lproj`.

2022-10-18 00:25 UTC, uiryuu approved these changes

2022-10-18 00:25 UTC, merged