Improve reliability of click detection in player window by adding minimum threshold for drag
iina/iina pull request #4232
Opened 2023-02-20 07:26 UTC by svobs

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4231.

---

**Description:**

This updates the click detection in `MainWindowController` and adds a requirement that after mouseDown the user must drag the cursor at least 2pts distance for drag to start.

A given `mouseDown`/`mouseUp` pair is processed as either a click or a drag, but not both. The out-of-the-box behavior in Cocoa is unfortunately not very useful to take on its own: the `mouseDragged` callback is called with very high sensitivity (particularly with trackpad actions); `mouseDragged` will get called for drag distances of just a fraction of a pixel. This is both not very useful as a an actual drag distance, and actively harmful because it results in clicks/taps appearing to be ignored from the user's standpoint.

After some testing and tweaking, I concluded that a drag start threshold requirement of 2pts is all that's needed to ensure that clicks are registered reliably *and* there is no noticeable burden on actual drag attempts. Note that 2pts is all that's needed to *start* the drag, so if the user's goal is to move their player window by only 1pt, they will have to first drag it by 2 pts to register the drag, then drag it back by 1 pt to position it. I believe this behavior is similar to how CAD & layout software usually works, but as a video player it's expected to be very rare that any user will be making such fine adjustments anyway.

2023-02-21 21:33 UTC, low-batt commented
See my long comment in the issue. I'm thinking the user should be able to control this, but wait to see what others think.

2023-03-29 07:29 UTC, uiryuu requested changes
LGTM

2023-03-29 07:29 UTC, uiryuu commented on iina/MainWindowController.swift
> +fileprivate let minimumInitialDragDistance: CGFloat = 4.0
Please add some comments to clarify that the intended distance is 2 instead of 4 since we are using spared distance.

2023-03-29 22:48 UTC, svobs commented
Made another commit. The whole "squared" thing was due to copying an answer from StackOverflow, but it's silly to focus on avoiding a square root in this case because it won't affect performance in any meaningful way. Tweaked the drag distance so it is 3.0 pts instead of 4.0, but shouldn't make much difference.

2023-03-30 02:36 UTC, uiryuu approved these changes

2023-03-30 03:11 UTC, merged

2023-03-30 03:12 UTC, uiryuu commented
Thanks!