Fix: cursor lost when dragging clip view edges
iina/iina pull request #4302
Opened 2023-03-28 02:11 UTC by yuxiqian

Start IINA and play a video, open "Quick Settings" panel and select Crop - "Custom...". Drag the right edge over the left boundary and release. The cursor that should appear on the left edge will be lost.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4299 .

---

**Description:**

In `CropBoxView.swift`, it uses a `boxRect: NSRect` to store currently selected clip region, and drew cursor rects around it to capture dragging events. `boxRect.size` can be negative, indicating that it expands southwest from its origin point.

However, `NSRect.width` and `NSRect.height` are always positive, so the cursor rects (colored in red) are misplaced.

<img width="1192" alt="A screenshot of misplaced cursor rects" src="https://user-images.githubusercontent.com/34335406/228108200-d344e041-ccc6-4c15-b24c-819357b1dd79.png">

Using `NSRect.size.width` and `NSRect.size.height` should fix this problem.

2023-03-28 02:30 UTC, uiryuu reviewed
We always welcome new contributors! And I didn't notice that it's not needed to normalize after `mouseUp`, so your solution is actually better than mine! Please re-open your pull request if you want and follow the code review :)

2023-03-28 02:30 UTC, uiryuu commented on iina/CropBoxView.swift
> +    rectTop = makeRect(x, y-2, w, 4)
You can call `standardized` after `NSMakeRect`, which does the exact same thing as your help function

2023-03-28 02:43 UTC, yuxiqian commented on iina/CropBoxView.swift
> +    rectTop = makeRect(x, y-2, w, 4)
Thanks for your advice! Reopened and cleaned up code.

2023-03-28 02:45 UTC, uiryuu requested changes

2023-03-28 02:45 UTC, uiryuu commented on iina/CropBoxView.swift
> +
Please remove trailing spaces

2023-03-28 02:47 UTC, yuxiqian commented on iina/CropBoxView.swift
> +
Done

2023-03-28 09:34 UTC, uiryuu approved these changes

2023-03-29 02:45 UTC, merged

2023-03-29 02:46 UTC, uiryuu commented
Thanks