Update highlight of sidebar tab buttons so they all match (fixes issue #4332)
iina/iina pull request #4378
Opened 2023-04-22 09:59 UTC by svobs

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4332.

---

**Description:**

Analysis: For newer versions of MacOS (10.14+), the 3 Quick Settings tab buttons are displayed all in bold, and the active tab's button text tint is set to pure black. However, the Playlist & Chapters tabs were following (what looks like) an older scheme: the active tab was bold, and the other tab was not bold; neither had a special tint. (The Quick Settings tabs fall back to this behavior for older versions of MacOS).

This update changes Playlist & Chapters so that they match the behavior of the other three

2023-04-23 03:40 UTC, svobs commented
Update: found a case which I missed, where the Playlist was displayed in Music Mode right after starting IINA. Fixed in the latest commit.

2023-04-23 03:47 UTC, low-batt commented
For me the Playlist and Chapters tabs do not match. Looks like the Playlist font is bold and Chapters isn't?

2023-04-23 07:44 UTC, svobs commented
> For me the Playlist and Chapters tabs do not match. Looks like the Playlist font is bold and Chapters isn't?

Good catch. Made another commit to address this.

2023-04-23 23:43 UTC, low-batt approved these changes
Pulled PR, built, tested, looks good to me.

2023-04-29 02:20 UTC, uiryuu requested changes

2023-04-29 02:20 UTC, uiryuu commented on iina/ExtendedColors.swift
> +@available(OSX 10.14, *)
```suggestion
@available(macOS 10.14, *)
```

2023-04-29 02:27 UTC, svobs commented on iina/ExtendedColors.swift
> +@available(OSX 10.14, *)
Updated in latest commit

2023-04-29 02:32 UTC, merged

2023-04-29 02:32 UTC, uiryuu commented
Thanks!