Show "resizeLeftRight" cursor when able to resize the playlist sidebar, expand activation width
iina/iina pull request #4472
Opened 2023-06-27 06:48 UTC by svobs

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [ ] This implements/fixes issue #.

---

**Description:**

https://github.com/iina/iina/assets/2213815/2b98ae23-9b4e-422d-a1d1-0f331df11d22

Makes resizing the width of the Playlist sidebar easier & more intuitive:
1. Change cursor to `NSCursor.resizeLeftRight` when hovering inside the resize activation rect.
2. Expand width of the activation rect from 4 pts to 10 pts.

2023-07-25 18:40 UTC, low-batt requested changes
Would be good to rebase this with `develop` to get the CI build to work.

When I tried it the cursor changed to the resize cursor at the edge of the playlist. I then moved the cursor to the left. The playlist did not change size. I ended up with a resize cursor in the middle of the window.

As can be seen in the Human Interface Guidelines [here](https://developer.apple.com/design/human-interface-guidelines/pointing-devices) there are 3 different resize cursors. Experiments with the [Dictionary](https://support.apple.com/guide/dictionary/welcome/mac) app and resizing its side panel I see it switching between [resizeLeftRight](https://developer.apple.com/documentation/appkit/nscursor/1525074-resizeleftright) and [resizeRight](https://developer.apple.com/documentation/appkit/nscursor/1526314-resizeright) or [resizeLeft](https://developer.apple.com/documentation/appkit/nscursor/1535416-resizeleft) once a maximum or minimum size has been reached. Testing with [Preview](https://support.apple.com/guide/preview/welcome/mac) I saw this same behavior with its side panel.

I think IINA needs to match the behavior of the Apple applications and switch between the 3 cursors different resize cursors.

2023-07-26 05:26 UTC, svobs commented
> As can be seen in the Human Interface Guidelines [here](https://developer.apple.com/design/human-interface-guidelines/pointing-devices) there are 3 different resize cursors.

Well that's fun. Somehow I never noticed when that feature appeared.

A bit burnt out on these tweaks at the moment and have lots of non-IINA-related work piled up, but will get back to this soon.

2023-07-26 16:39 UTC, low-batt commented
The new commit has to do with miniturizing the Music Mode window…

2023-07-26 19:40 UTC, svobs commented
> The new commit has to do with miniturizing the Music Mode window…

Sorry. Forgot I committed to `develop` before I branched for that one, instead of the other way around. Didn't back it out and ended up rebasing with that commit. WIll avoid that problem in the future by rebasing directly from `origin/develop`...

Fixed the rebase. Still need to fix the cursor though.

2025-05-27 03:33 UTC, svobs commented
Addressed by PRs #5523 & #5521; closing

2025-05-27 03:33 UTC, closed without merging

2025-06-12 00:23 UTC, sourface94 commented
> Addressed by PRs #5523 & #5521; closing

Hey how doI resize the playlist window through the UI? Its not clear through those PRs