Fixes to Quick Settings localization regressions (fixes #4481)
iina/iina pull request #4484
Opened 2023-07-10 00:45 UTC by svobs

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4481.

---

**Description:**

1. Change IDs for several fields to their former values, so that they match the ones expected by `QuickSettingsViewController.strings` files.
2. Change some uses of "..." to "…" in the XIB, to match standard style
3. Regenerated `iina/en.lproj/QuickSettingViewController.strings` in XCode. Include some fields which appeared to be missing. _Requesting feedback on this._
4. Update `vFD-HU-RVz.title` to `iuN-rN-jT7.ibShadowedLabels[6]` for `Custom…` segmented button because it has changed form.

2023-07-11 04:00 UTC, low-batt requested changes
Missed one on the `VIDEO` tab. And since an update is needed might as well include the fix for issue #4482. Trivial fix to this same XIB. See my comment in that issue.
![issue-4481](https://github.com/iina/iina/assets/86170219/da5c9f3d-c9a9-48d4-9b15-1632a4b6f8ff)

2023-07-12 03:53 UTC, svobs commented
I included the fix for #4482 and updated the description to note this.

> Missed one on the VIDEO tab.

Forgot to ask about that - it's item 4 in the description. I included the fix in the `en` localization, but wasn't clear if I was to update all versions of `QuickSettingViewController.strings`. I'm fine with doing that - just wanted to ask first, because I've been told in other cases to limit my changes to `en`.

There's actually a lot I'm still unclear about as it comes to localizations & the workflow to/from Crowdin. I guess I've been assuming that one of of the core devs had ownership over it and would do some kind of regeneration from Crowdin and/or validation before each release.

2023-07-12 05:02 UTC, low-batt commented
I believe the only update the en rule applies. I'm confused as to why it can't be linked to the old translation text. I guess we will need to check in with others as to how to handle this.

2023-07-12 06:21 UTC, lhc70000 commented
I agree that we should release a fix for this (together with the VP9 hardware decoding problem).

However I'm not sure whether crowdin will handle ID changes correctly. I will test it out today or tomorrow with @uiryuu.

2023-07-12 08:21 UTC, merged

2023-07-12 08:22 UTC, uiryuu commented
It seems the previous translations are still left in the .strings files; merge this to see how Crowdin behaves...

2023-07-12 08:32 UTC, uiryuu commented
![image](https://github.com/iina/iina/assets/20237141/751a259d-b9bb-4a12-8346-61c9b562d4ed)

After applying this PR, the missing strings are back!

2023-08-14 14:19 UTC, raisin8010 commented
It seems there is still one string not fixed...
<img width="366" alt="SCR-20230814-thgq" src="https://github.com/iina/iina/assets/55045806/2e33a822-73da-458b-a219-f0c5ac9ea1bb">

2023-08-17 04:06 UTC, svobs commented
@woshiniming007 thank you for reporting, but next time please report as a new defect because this one has already been closed. I have listed it in a new defect, #4588.