Make open/save dialogs block window input while open (fixes #4583)
iina/iina pull request #4590
Opened 2023-08-17 07:35 UTC by svobs

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4583.

---

**Description:**

This fixes the use of arrow key navigation in the following open/save dialogs:
1. "Load external audio file" (Audio Settings sidebar)
2. "Load external subtitle" (Subtitles menu)
3. "Load subtitle..." (Subtitles Settings sidebar)
4. "Save downloaded subtitle" (Subtitles menu)

Some users were complaining that mpv bindings were getting activated in response to arrow keys when they wanted to use them to navigate within the file picker dialog. This ensures that they will work, but it comes at some cost. They now use Apple's tyrannical modal dialog state, which clings onto the window and won't let the user do anything with it until the dialog is dismissed. I'm not a fan, although using it is probably adheres more closely to Apple's HIG than using an independent window.

2023-08-18 18:57 UTC, low-batt commented
I too am not a fan of sheets, but…

On the question of what the HIG has to say, [Panels](https://developer.apple.com/design/human-interface-guidelines/panels) says:
> In a macOS app, a panel typically floats above other open windows providing supplementary controls, options, or information related to the active window or current selection.

The HIG section on sheets can be found [here](https://developer.apple.com/design/human-interface-guidelines/sheets#macOS).

I did not find the HIG that helpful. Looking at the behavior of `TextEdit` the convention seems to be that you use a floating panel for an operation that is not tied to a specific window, but if the operation is specific to a particular window then a sheet is used.

Applied to IINA that suggests operations such as loading an external subtitle file should be a sheet as it is to be applied to a specific window.

This certainly is a significant change that will be noticed by users.

The `NSOpenPanel` put up by `AppDelegate.openFile` does not exhibit the problem of passing key strokes to the player window. That panel is displayed using [runModal](https://developer.apple.com/documentation/appkit/nssavepanel/1525357-runmodal).

As a side issue, that portion of the HIG also contains the following which IINA is violating:
> **Refer to panels by title in your interface and in help documentation.** In menus, use the panel’s title without including the term panel: for example, “Show Fonts,” “Show Colors,” and “Show Inspector.”

2023-08-18 19:04 UTC, low-batt requested changes
The menu item `Save Current Playlist…` under the `File` menu still exhibits the the problem.

2023-08-23 05:26 UTC, svobs commented
> The NSOpenPanel put up by AppDelegate.openFile does not exhibit the problem of passing key strokes to the player window. That panel is displayed using [runModal](https://developer.apple.com/documentation/appkit/nssavepanel/1525357-runmodal).

This is very interesting. I suppose it's a special case because its action is attached to `AppDelegate` and thus automagically considered to be an app-wide feature (maybe), rather than an action tied to a player window. However it blocks key events to all the windows in the app, which is even less desirable. I think I'd be happier with sheets if they were easier to resize vertically and move around - seems very unintuitive that you are expected to grab the title bar of the window behind it, the one which is otherwise blocked from all events.

> The menu item Save Current Playlist… under the File menu still exhibits the the problem.

Added a new commit to include this.

> As a side issue, that portion of the HIG also contains the following which IINA is violating:
> 
> > Refer to panels by title in your interface and in help documentation. In menus, use the panel’s title without including the term panel: for example, “Show Fonts,” “Show Colors,” and “Show Inspector.”

Ah, do you mean that `Load Subtitle...`, et al, should be renamed `Open Subtitle...`? Yeah I think I agree with that - it would be more "Mac-like".

2023-08-23 21:46 UTC, low-batt commented
No, it was this part of the HIG requirement I was thinking of:
> without including the term panel

Which means the menu item `Show Video Panel` and others are clearly in violation. Bummer. Right now I think we should pretend I did not notice this.

2023-08-23 21:50 UTC, low-batt approved these changes
Pulled latest commit and tested. Changes look good.

2023-08-23 21:54 UTC, low-batt commented
By the way I'm now using the [GitHub CLI](https://cli.github.com/) to checkout PRs:
```text
gh pr checkout 4590
```

The CLI automatically handles the case where the author has forced pushed changes to the PR.

2023-12-26 13:06 UTC, uiryuu approved these changes
I think the proposed the changes are reasonable.

2024-01-02 13:03 UTC, merged