Fix chapter list not updating and/or crashing (issue #4696)
iina/iina pull request #4697
Opened 2023-11-25 08:26 UTC by svobs

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4696.

---

**Description:**

* Removes bad code from `PlayerCore.getChapters()` which returned early when chapter count == 0. This resulted in chapter list not getting updated in this situation.
* Fix crash by adding checks whether index is valid into chapters array wherever it is referenced.
* Generally fix potential concurrency pitfalls relating to chapters list (see comments in code).
* Chapter list reload triggers table reload. Not the other way around.

2023-12-26 03:09 UTC, low-batt commented on iina/PlaySliderCell.swift
>          var chapters = info.chapters
```suggestion
        let chapters = info.chapters
```

2023-12-26 03:13 UTC, low-batt commented on iina/MainMenuActions.swift
> +                 level: .error, subsystem: player.subsystem)
I think error is too strong for this situation. The user can trigger this. IINA recovers. There isn't an error that needs to be corrected. I would emit this as a debug level message.

2023-12-26 03:15 UTC, low-batt requested changes
Pulled PR, tested, confirmed crash no longer happens.

The variable in `PlaySliderCell` should be changed to be a let constant to correct a new compiler warning.

I would change the log level of that one message although that is not critical.

2023-12-26 04:22 UTC, svobs commented
> The variable in PlaySliderCell should be changed to be a let constant to correct a new compiler warning.
> I would change the log level of that one message although that is not critical.

Done. Committed (also rebased). In the XCode 15 release notes, I saw this:
> Fixed an issue where build warnings in Swift files sometimes disappeared after an incremental build.  (105421512)

Doesn't seem to be fixed in all cases, unfortunately.

2023-12-26 04:24 UTC, low-batt approved these changes
All looks good to me.

2023-12-26 04:34 UTC, low-batt commented
I have experienced that Xcode behavior where warnings are not shown as well. Very frustrating.

PRs are being merged for a 1.3.4 release. The main focus of this release is the switch to Open Subtitle's REST API as the old API is shutting down at the end of the year. This PR is on the list for that release.

2024-01-02 06:07 UTC, merged

2024-01-02 06:07 UTC, uiryuu commented
Thanks!