fix: avoid double percent-encode for url scheme
iina/iina pull request #4860
Opened 2024-03-30 07:44 UTC by xfoxfu

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #.

---

**Description:**

Remove manual percent-encoding for URL opened in URL scheme. This will make URLs with special characters no longer be encoded twice and thus openable.

Due to a recent change in Apple `URL.init`, URL will be encoded automatically, see: <https://developer.apple.com/documentation/foundation/url/3126806-init>

Therefore, if the URL is percent-encoded beforehand, it will be encoded a second time if `URL` is constructed.

```
URL Scheme:
iina://weblink?url=https://alist.xfox.me/d/Anime/%5BDMG%26VCB-Studio%5D%20Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!%20%5BMa10p_1080p%5D/%5BDMG%26VCB-Studio%5D%20Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!%20%5B01%5D%5BMa10p_1080p%5D%5Bx265_flac_aac%5D.mkv
Log:
16:01:57.099 [player0][d] Open URL: https://alist.xfox.me/d/Anime/%5BDMG&VCB-Studio%5D%2520Kono%2520Subarashii%2520Sekai%2520ni%2520Bakuen%2520wo!%2520%5BMa10p_1080p%5D/%5BDMG&VCB-Studio%5D%2520Kono%2520Subarashii%2520Sekai%2520ni%2520Bakuen%2520wo!%2520%5B01%5D%5BMa10p_1080p%5D%5Bx265_flac_aac%5D.mkv
URL-decoded:
16:01:57.099 [player0][d] Open URL: https://alist.xfox.me/d/Anime/[DMG&VCB-Studio]%20Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!%20[Ma10p_1080p]/[DMG&VCB-Studio]%20Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!%20[01][Ma10p_1080p][x265_flac_aac].mkv
```

This PR removes the first manual percent-encoding, which makes URL correct.

2024-03-30 18:30 UTC, low-batt commented
How do I reproduce the problem this PR fixes?

Running under macOS 14.4 I opened the following URL in Firefox:
```text
iina://weblink?url=https://example.com/d/Anime/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!.mkv
```

And I'm not seeing double percent encoding in IINA's log:
```text
14:26:02.770 [iina][d] URL event: iina://weblink?url=https://example.com/d/Anime/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!.mkv
14:26:02.770 [iina][d] Parsing URL iina://weblink?url=https://example.com/d/Anime/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!.mkv
14:26:02.771 [player0][d] Open URL: https://example.com/d/Anime/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!.mkv
14:26:02.771 [player0][d] Opening https://example.com/d/Anime/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!.mkv in main window
…
14:26:06.447 [mpv][e] [stream] error: Failed to open https://example.com/d/Anime/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!.mkv.
```

2024-03-30 18:48 UTC, xfoxfu commented
Interesting, it seems only having whitespaces in the URL is not sufficient to trigger the bug. Please try this URL:

<iina://weblink?url=https://example/%25foo%20bar.mkv>

```
03:47:28.786 [iina][d] URL event: iina://weblink?url=https://example/%25foo%20bar.mkv
03:47:28.786 [iina][d] Parsing URL iina://weblink?url=https://example/%25foo%20bar.mkv
03:47:28.786 [player0][d] Open URL: https://example/%25foo%2520bar.mkv
03:47:28.786 [player0][d] Opening https://example/%25foo%2520bar.mkv in main window
```

2024-03-30 19:38 UTC, low-batt commented
Thanks for the update. Reproduced for me now.

Very busy today. I will be taking a close look into this problem.

2024-03-31 21:51 UTC, low-batt requested changes
Excellent work tracking this problem to Apple's change. I really appreciate your investigation and proposed fix.

The call to `addingPercentEncoding` can't be fully removed because the new behavior is only present when running under macOS Sonoma and only if built with Xcode 15. Look for the suggested change.

I've created issue #4861 for this problem. See that issue for a full discussion. There are other places in the code that probably need to be updated. We'd want to be able to reproduce a problem before making changes.

2024-03-31 21:51 UTC, low-batt commented on iina/PlayerCore.swift
> +        Logger.log("Cannot parse url for \(str)", level: .error, subsystem: subsystem)
```suggestion
      // For apps built with Xcode 15 or later the behavior of the URL initializer has changed when
      // running under macOS Sonoma or later. The behavior now matches URLComponents and will
      // automatically percent encode characters. Must not apply percent encoding to the string
      // passed to the URL initializer if the new new behavior is active.
      var performPercentEncoding = true
#if compiler(>=5.9)
      if #available(macOS 14, *) {
        performPercentEncoding = false
      }
#endif
      var pstr = str
      if performPercentEncoding {
        guard let encoded = str.addingPercentEncoding(withAllowedCharacters: .urlAllowed) else {
          print("Cannot add percent encoding for \(str)")
          return
        }
        pstr = encoded
      }
      guard let url = URL(string: pstr) else {
        Logger.log("Cannot parse url for \(pstr)", level: .error, subsystem: subsystem)
```

2024-04-01 02:49 UTC, xfoxfu commented
Thanks for your suggestions, and I have tested on macOS Ventura with XCode 15.2 that the problem has been resolved, but I do not have access to older macOS or XCode.

2024-04-01 15:01 UTC, uiryuu approved these changes
Tested this PR on two machines:
1. MacOS Sonoma w/ Xcode 15.2
2. MacOS Monterey w/ Xcode 13.4.1

IINA used for testing was compiled locally on the corresponding machine. The `#if compiler(>=5.9)` check works as intended. And confirmed the proposed fix doesn't break when IINA is built by older version Xcode.

However, during testing, I found that this URL: `iina://weblink?url=https://example/%25foo%20bar.mkv` cannot be parsed on the older machine. Because we allowed `.urlAllowed`, which is customized in here:

https://github.com/iina/iina/blob/3f02bf0b37e9f13be8dcebc570dbf6b2b0cdad62/iina/Extensions.swift#L451C1-L462C2

This is where we manually added "%" into the CharSet, so that the `pstr` becomes `https://example/%foo%20bar.mkv` after `addingPercentEncoding` and thus invalid for further parsing. Not sure why we manually added "%" before. 

This is *not* caused by this PR, so this one is safe to merge.

2024-04-01 15:18 UTC, xfoxfu commented
Actually, `iina://weblink?url=https://example/%25foo%20bar.mkv` is not leading to a valid URL by RFC 3986. The `url` query parameter will be `https://example/%foo bar.mkv` where the `%` is not properly encoded to `%25`.

I think allowing `%` in URL has practical use since the URL could be `https://example.com/%2520.mkv`, where the filename is `%20.mkv` (not ` .mkv`), and in this case, the `%` before `2520` should not be encoded to preserve `%25` as a whole.

A better way of handling these "endless" corner cases easily could be utilizing the new `URL` behavior, while backporting a similar feature to older platforms which does not support `URL(string: encodingInvalidCharacters:)`.

2024-04-01 21:29 UTC, low-batt approved these changes
I pulled the latest commits and tested under Ventura and Sonoma.
Changes look good to me.

2024-04-01 21:34 UTC, merged

2024-04-01 21:41 UTC, low-batt commented
I've created issue #4862 for the problem with `%`. We should continue the discussion in that issue.

@xfoxfu A final big THANK YOU for investigating, reporting and fixing this problem. Very timely has we are moving closer to a release that fixes regressions. Would have been bad to miss this one.