Fix some deprecated issues
iina/iina pull request #5130
Opened 2024-08-12 01:51 UTC by siieo

Works fine in intel and Apple Silicon

- [X] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [X] This implements/fixes issue #.

---

**Description:**

In reviewing the code, I identified several deprecated APIs that need to be updated to ensure compatibility with the latest macOS versions. To address these issues, I have replaced the deprecated methods with their modern counterparts, aligning with current best practices and API recommendations.

2024-08-12 06:34 UTC, uiryuu requested changes

2024-08-12 06:34 UTC, uiryuu commented on iina/MainWindowController.swift
> +    let buttons = buttons
```suggestion
```
There's no reason to shadow `buttons` here, just delete it.

2024-08-12 06:34 UTC, uiryuu commented on iina/PlaySliderCell.swift
> +      shadow.shadowColor = NSColor.separatorColor // Use the separatorColor for shadows
```suggestion
      shadow.shadowColor = .separatorColor
```

2024-08-12 06:34 UTC, uiryuu commented on iina/PlaySliderCell.swift
> +      NSColor.separatorColor.setStroke() // Use separatorColor instead of controlShadowColor
```suggestion
      NSColor.separatorColor.setStroke()
```

2024-08-12 06:36 UTC, uiryuu commented
I'm not sure whether or not `separatorColor` is the correct color to use here

2024-10-12 12:29 UTC, low-batt requested changes
The code in `FFmpegController` is needed and must not be removed. See my comment on the change for details.

2024-10-12 12:29 UTC, low-batt commented on iina/FFmpegController.m
> -            cgColorSpace = CGColorSpaceCreateWithName(kCGColorSpaceITUR_2020_PQ_EOTF);
This code **must not** be removed.

Thank you very much for working to reduce the deprecated warnings. The IINA project considers it important to fix compiler warnings. Your help is appreciated. Unfortunately **Xcode is BROKEN** and can trick you into removing code that is needed. The file `Configs/Deployment.xconfig` contains:
```text
MACOSX_DEPLOYMENT_TARGET = 10.15
MACOSX_DEPLOYMENT_TARGET[arch=arm64] = 12
```

This has confused Xcode and it is emitting deprecated messages as if the minimum macOS version for IINA is macOS Monterey. It is not. The minimum macOS version is macOS Catalina. If you are building on a Mac with a M1 chip in Xcode change your build destination to `My Mac (Rosetta)` then clean and rebuild. You will see many of these deprecated warnings disappear. To do that you may have to enable the Rosetta destination. Apple is pushing developers away from Rosetta by hiding that destination in Xcode by default. If you have trouble enabling Rosetta another way to see this is to change the above file to use `10.15` for `arch=arm64` then clean and rebuild.

2024-10-12 12:29 UTC, low-batt commented on iina/FFmpegController.m
> -          cgColorSpace = CGColorSpaceCreateWithName(kCGColorSpaceDisplayP3_PQ_EOTF);
macOS 10.15 is still supported, so this code can not be removed.

2025-04-07 04:00 UTC, closed without merging